spring:
  application:
    name: spring-boot-admin-console
  cloud:
    config:
      enabled: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

spring.boot.admin.url: http://localhost:8080
management.security.enabled: false

spring.boot.admin.routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream

spring.boot.admin.turbine:
  clusters: default
  location: turbine